#!/bin/bash

#
# This message is shown on login
#



IPADDR=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')

echo ""
echo ""
echo -e '\e[0;34m'"infracamp's KickGuest VMware :: happy containers"
echo -e '\e[0m'"------------------------------------------------"
echo -e '\e[1;37m'
echo "SSH login.........: ssh user@$IPADDR (No password)"
if [ $IPADDR = "10.127.127.127" ]
then
echo "........or........: ssh user@local.infracamp.org"
fi;

echo ""

echo "Browser...........: http://$IPADDR"
if [ $IPADDR = "10.127.127.127" ]
then
echo "........or........: http://local.infracamp.org"
fi;

echo ""

echo "Mounted folders.........: /mnt"
echo -e "\e[0m"
echo "Change keyboard layout..: sudo dpkg-reconfigure keyboard-configuration"
echo ""


if [ -e /home/user/.ssh/id_*.pub ]
then
    echo "------ Your SSH Public Key: ----------";
    echo $(cat  /home/user/.ssh/id_*.pub);
    echo "--- Copy this key to github/gitlab ---";
fi;

echo ""
echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "Questions? visit http://infracamp.org"
echo ""
echo "Type: 'll' to see all files and 'cd <dirname>' to move the directory"
echo ""